[project]
name = "scrapingtool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "streamlit",
  "scrapegraphai"
]


[project.scripts]
scrapingtool = "scrapingtool.app:main"